Source-Python-Dev-Team/Source.Python

addons/source-python/packages/source-python/engines/precache.py
Server crashes if engines.precache.Model object is being created on server load.
For example, I have simple plugin:
```python
from engines.precache import Model
test_model = Model('models/player/t_leet.mdl')
```
which is loaded through autoexec.cfg. When I start the server it crashes with this error:
```
Host_Error: CVEngineServer::PrecacheModel: 'models/player/t_leet.mdl' overflow, too many models
```
I don't know if there is the same problem with Decal and Generic class, but this fix will work for them too :smiley: 
Tested on CS:S, Linux (custom build from Jan 15)/Windows (official Jan 15 build).
=> Fixed server crash when precaching on server startup

addons/source-python/packages/source-python/entities/constants.py
The usage of entities.constants.damage_types to define damage type in TakeDamageInfo object cause boost exception:
```
Boost.Python.ArgumentError: Python argument types in
None.None(TakeDamageInfo, damage_types)
did not match C++ signature:
None(class CTakeDamageInfo {lvalue}, int)
```
Code:
```python
from basetypes import TakeDamageInfo
from entities.constants import damage_types
take_damage_info = TakeDamageInfo()
take_damage_info.type = damage_types.GENERIC
```
=> Fixed error when using damage_type enum in TakeDamageInfo

src/core/modules/commands/server_commands_wrap.cpp
When I register ServerCommand without help text in arguments my Linux CS:S server crashes.
```python
from commands.server import ServerCommand
@ServerCommand('test_me')
def test_me_command(command):
print("It works!")
```
This one works fine:
```python
@ServerCommand('test_me', 'Help text!')
```
Same problem when using `server_command_manager.register_commands` directly.
The segfault was caused by passing `NULL` to `strdup`.
Windows doesn't have this problem and I haven't tested how this fix works on Windows server, but everything should be fine... I think... ~~Any way I don't have Visual Studio installed.~~
=> Fixed crash caused by ServerCommand registration without Help text.

addons/source-python/packages/source-python/entities/specials.py
One "t" is missing :)
https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/src/core/modules/basetypes/basetypes_wrap_python.cpp#L365
=> Fixed typo in entities/specials.py

src/core/modules/filters/filters_recipients.cpp
It is possible to set the classname keyvalue of a player entity to something other than "player". Some custom maps make use of this in conjunction with filter_activator_class for various things.
=> Fix usermessages not being sent when player classname is changed.

addons/source-python/packages/source-python/menus/radio.py
The slot for the menu close button needs to be 0 instead of 10 for games other than CS:GO/BMS.
Not sure if this is the best way to fix it - let me know if it needs any changes.
=> Fix menu close button slot.

addons/source-python/packages/source-python/events/hooks.py, addons/source-python/packages/source-python/events/listener.py
Event's name is still required when registering the same callback for multiple events:
@Event('player_spawn', 'player_jump')
def on_event(**eargs):
print('Player with userid of {userid} triggered {event_name}.'.format(**eargs))
I chose to use `'event_name'` since it can still be grabbed in the parameters (`'event name'` could not be):
@Event('player_spawn')
def on_spawn(event_name, **eargs):
pass
And simply using `'name'` felt a little ambiguous.
=> Added 'event_name' to event's kwargs

addons/source-python/data/source-python/entities/CBaseCombatWeapon.ini
Difficult to notice, took a while to figure out
=> It it "LocalActiveWeaponData" according to CS:S.

addons/source-python/packages/source-python/commands/command.py
Before if you did this:
@ClientCommand('test')
@SayCommand('test')
def test(*args):
print('test() was called')
It would raise an error because `_BaseCommand.__call__()` returns the command instance itself, as opposed to the original `test` function. This would cause `SayCommand` to attempt to register the `ClientCommand` instance as a callback, which would fail.
@Ayuto already hotfixed this [here](https://github.com/Source-Python-Dev-Team/Source.Python/commit/f1a00610cd3c17d6d440f50413707209026819c1), but I believe that's just a workaround and doesn't solve the actual issue: the decorator is returned instead of the decorated function. Also, his workaround still doesn't allow one to call the `test()` function after decorating it as a command. The following code wouldn't work because `test` …
=> Return the original callback from commands' __call__

addons/source-python/packages/source-python/commands/filter.py, addons/source-python/packages/source-python/hooks/base.py
Should be quite self-explanatory. Even if they're not currently used by anything, this improves extendability and if someone wants to use kwargs or the return value, let them.
=> Kwargs and return values to filters and hooks' __call__

addons/source-python/packages/source-python/entities/specials.py
By new conversion functions I mean the ones that don't provide optional 'raise_exception' keyword argument any more.
=> Updated entities.specials to support new conversion functions

src/CMakeLists.txt, src/core/modules/engines/engines_tools_wrap.cpp, src/core/sp_main.cpp
Hi,
This change wraps the IEngineTool interface which contains some very useful functionality. Currently, I've only wrapped the stuff that isn't covered by the IVEngineServer wrapper. I've also skipped stuff that only works client-side. This should also help solve issue #97.
=> Initial wrap of useful functions from the IEngineTool interface.

addons/source-python/packages/source-python/core/__init__.py, addons/source-python/packages/source-python/listeners/tick.py, addons/source-python/packages/source-python/plugins/manager.py
=> Add weakref-based AutoUnload class to allow instances to be garbage collected

addons/source-python/packages/source-python/players/dictionary.py
Since the `Player` entity class [got a `from_userid()`](https://github.com/Source-Python-Dev-Team/Source.Python/commit/8a45c575b95e8fcba8fc419e0a02f6c8bfdc0cba), I think `PlayerDictionary` should have one too for consistency and easier usage in events.
=> Added from_userid() for PlayerDictionary

addons/source-python/packages/source-python/menus/base.py
This allows one to define the menu before its callbacks while keeping the code clean.
=> Added decorators for adding callbacks to menus

addons/source-python/data/source-python/entities/CBaseCombatWeapon.ini, addons/source-python/docs/source-python/source/contributing/reporting-a-bug.rst, addons/source-python/packages/source-python/entities/entity.py, addons/source-python/packages/source-python/weapons/_entity/__init__.py, addons/source-python/packages/source-python/weapons/_entity/csgo/__init__.py
Resolved confusion between clip/secondary_fire_clip attributes defined in data files and get_clip/set_clip/... methods in `_entity/__init__.py`
Special thanks to @Mahi for consulting this PR
=> Multiple improvements / bug fixes to player_weapons_update2 branch

addons/source-python/packages/source-python/weapons/restrictions.py
More information:
http://forums.sourcepython.com/viewtopic.php?f=20&p=9791#p9791
=> Fixes weapon restriction

addons/source-python/packages/source-python/engines/sound.py
Fixes #221.
I feel like I'm missing something with this fix, but it works with some light testing.
=> Fix Sound.is_precached and StreamSound.is_precached performance

addons/source-python/packages/source-python/effects/__init__.py
=> Improve performance of effect wrappers.

addons/source-python/docs/source-python/source/developing/modules/messages.hooks.rst, addons/source-python/docs/source-python/source/developing/modules/messages.impl.rst, addons/source-python/packages/source-python/messages/hooks.py, addons/source-python/packages/source-python/messages/impl.py, src/core/modules/messages/messages.h, src/core/modules/messages/messages_wrap.cpp
This adds the feature requested in #180.
Are there any other user messages that should be implemented?
=> Add user message hooks

addons/source-python/data/source-python/weapons/csgo.ini
During testing of my plugin, I figured out that there is an inconsistency between the INI file and the actual values for said weapons. The recent weapon updates for CS:GO might have been the reason for that.
=> Weapon Data: Fix CS:GO clip & maxammo values for negev, hkp2000 and tec9

addons/source-python/packages/source-python/menus/base.py, addons/source-python/packages/source-python/menus/esc.py, addons/source-python/packages/source-python/menus/radio.py
Simple usage example:
```python
from menus import PagedMenu
from menus import PagedOption
main_menu = PagedMenu(
[
PagedOption('Say Hi', 0),
PagedOption('Say something else', 1)
], title='Main Menu'
)
@main_menu.register_select_callback
def main_menu_select(menu, index, option):
print(option.text)
@main_menu.register_close_callback
def main_menu_closed(menu, index):
player = Player(index)
print(f'Player {player.name} closed {menu.title}')
```
If you have any change requests, post them here :)
=> Menus: Add register_close_callback decorator

src/core/modules/commands/commands_client.cpp, src/core/modules/commands/commands_say.cpp, src/core/modules/commands/commands_server.cpp
Fixed names starting with / and ! (and probably others, as well) not being registered properly.
I'm not entirely sure this is the best way to fix, which is why I created a pull request instead of just merging into master.  It does work properly, though, for my testing with GunGame.
Before this fix, none of my say commands that started with ! or / were working.  I added some debug messages in `src/core/modules/commands/commands.h` where the comparisons are made, and all of the say commands that started with / or ! showed as a bunch of weird symbols.  That led me to believe that I needed to make copies before registering.
I believe I could also do this by storing all of these as attributes in GunGame itself, so they persist.  However, I don't necessarily believe that is the correct action …
=> Fixed commands not registering properly when given strings are not persistent

addons/source-python/packages/source-python/messages/base.py
This adds `UserMessageCreator.send_reliable()` to make use of the new `RecipientFilter.reliable` attribute in https://github.com/Source-Python-Dev-Team/Source.Python/commit/cb7a8dc42d8293c75e3d0b4fe092475429139dc6 (thanks to @Ayuto for adding that!)
=> Make SayText, SayText2 and TextMsg messages reliable by default

addons/source-python/data/source-python/entities/csgo/CPointWorldText.ini
Just adding some keyvalues and properties for the awesome [point_worldtext](https://developer.valvesoftware.com/wiki/Point_worldtext) entity.
The **message** keyvalue doesn't work unless it's hardcoded, not sure why.
=> Added CPointWorldText data

addons/source-python/data/source-python/entities/orangebox/tf/CBaseCombatCharacter.ini, addons/source-python/data/source-python/entities/orangebox/tf/CBaseCombatWeapon.ini, addons/source-python/data/source-python/entities/orangebox/tf/CBasePlayer.ini, addons/source-python/data/source-python/entities/orangebox/tf/CTFPlayer.ini
Looks like all of the TF offsets were outdated.
=> Updated TF offsets.

addons/source-python/data/source-python/weapons/constants/orangebox/cstrike/WeaponSlot.ini, addons/source-python/data/source-python/weapons/csgo.ini, addons/source-python/data/source-python/weapons/cstrike.ini, addons/source-python/data/source-python/weapons/hl2mp.ini
Seems the values were offset by 1.
=> Changed the slot values to be in line with Valve's weapon slots.

addons/source-python/packages/source-python/messages/colors/saytext2.py
```python
from filters.players import PlayerIter
from messages.colors.saytext2 import GREEN
from messages.colors.saytext2 import ORANGE
from messages.colors.saytext2 import DARK_BLUE
from messages.colors.saytext2 import DULL_RED
from messages.colors.saytext2 import PINK
from messages.colors.saytext2 import DARK_BLUE
from messages.colors.saytext2 import YELLOW
from messages.colors.saytext2 import GRAY
from messages.colors.saytext2 import BRIGHT_GREEN
from messages.colors.saytext2 import RED
from messages.colors.saytext2 import BLUE
from messages.colors.saytext2 import LIGHT_BLUE
from messages.colors.saytext2 import PALE_RED
from messages.colors.saytext2 import WHITE
MY_COLORS = {
'GREEN': GREEN,
'ORANGE': ORANGE,
'DULL_RED': DULL_RED,
'PINK': PINK,
'DARK_BLUE': DARK_BLUE,
'YELLOW': YELLOW, …
```
=> Add SayText2 colors package to message module (fix issue #252)

addons/source-python/data/source-python/entities/bms/CBaseCombatCharacter.ini, addons/source-python/data/source-python/entities/csgo/CBaseCombatCharacter.ini, addons/source-python/data/source-python/entities/gmod/CBaseCombatCharacter.ini, addons/source-python/data/source-python/entities/l4d2/CBaseCombatCharacter.ini, addons/source-python/data/source-python/entities/orangebox/CBaseCombatCharacter.ini, addons/source-python/data/source-python/entities/orangebox/tf/CBaseCombatCharacter.ini
When working with armor (CSS, CSGO) or critical hits (TF2), [CBaseEntity::OnTakeDamage](https://github.com/alliedmodders/hl2sdk/blob/0ef5d3d482157bc0bb3aafd37c08961373f87bfd/game/server/baseentity.cpp#L1376) gives incorrect values. I found out that [CBaseCombatCharacter::OnTakeDamage_Alive](https://github.com/alliedmodders/hl2sdk/blob/0ef5d3d482157bc0bb3aafd37c08961373f87bfd/game/server/basecombatcharacter.cpp#L2463) gives the correct values, so I've added the data for all supported games.
```python
from entities import TakeDamageInfo
from entities.entity import BaseEntity
from entities.hooks import EntityCondition, EntityPreHook
@EntityPreHook(EntityCondition.is_player, 'on_take_damage')
def on_take_damage_pre(stack_data):
base_entity = BaseEntity._obj(stack_data[0])
info = …
```
=> Added CBaseCombatCharacter::OnTakeDamage_Alive data.

addons/source-python/data/source-python/entities/CBaseEntity.ini, addons/source-python/docs/source-python/source/developing/modules/players._base.rst, addons/source-python/packages/source-python/players/_base.py, addons/source-python/packages/source-python/players/engines/csgo/__init__.py, src/CMakeLists.txt, src/core/modules/entities/entities_entity.h, src/core/modules/entities/entities_entity_wrap.cpp, src/core/modules/players/players_entity.cpp, src/core/modules/players/players_entity.h, src/core/modules/players/players_wrap.cpp
Just like the [Entity changes](https://github.com/Source-Python-Dev-Team/Source.Python/pull/235) last year, but now for the Player class.
This PR removes the properties from the data files that have been added to the BaseEntity class statically, because we don't need them anymore.
The PR also moves all player properties to a class called PlayerMixin. The PlayerMixin class is mixed into the class ``players._base.Player``. This is done to gain major speed improvements (85 - 125 times faster depending on the property). Moreover, these properties are now documented on the wiki.
I have also moved the game specific properties to PlayerMixin. If you access one of those properties in a different game, you will get the following error:
``ValueError: Unable to find property …
=> Player class updates

addons/source-python/data/source-python/entities/csgo/CBasePlayer.ini
Referenced from alliedmodders/sourcemod@bef8562de58cc25a52266cd51f92c74d62f26db1
Not tested on Windows.
=> Fix #285, thanks to AlliedModders/SourceMod

addons/source-python/data/source-python/entities/csgo/CCSPlayer.ini
Additional fix to #285.
Not tested on Windows.
=> Fixed CS:GO mvps and clan_tag offsets.

addons/source-python/packages/source-python/players/_base.py, addons/source-python/packages/source-python/weapons/_base.py, src/core/modules/players/players_entity.cpp, src/core/modules/players/players_entity.h, src/core/modules/players/players_wrap.cpp, src/core/modules/weapons/weapons_entity.cpp, src/core/modules/weapons/weapons_entity.h, src/core/modules/weapons/weapons_entity_wrap.cpp, src/core/utilities/wrap_macros.h
See: https://github.com/Source-Python-Dev-Team/Source.Python/issues/287
=> Fixed Player/Weapon method resolution order

addons/source-python/packages/source-python/entities/_base.py, addons/source-python/packages/source-python/players/_base.py, addons/source-python/packages/source-python/weapons/_base.py
I was curious about the feasibility of the caching @Ayuto suggested into [#284](https://github.com/Source-Python-Dev-Team/Source.Python/pull/284#issuecomment-557653995) so I played a bit with the idea and ended with this implementation. Entity instances are cached by default, unless `caching=False` is passed to the constructor. So, if users want their private instances for whatever reason, they can do so. Ran the following code to time the difference and the results are considerable:
```python
from time import time
class Cached(Player):
pass
t = time()
for i in range(1000000):
Cached(1).name
print('Cached:', time() - t)
class NotCached(Player):
pass
t = time()
for i in range(1000000):
NotCached(1, caching=False).name
print('NotCached:', time() - t)
``` …
=> Added entity instances caching.

addons/source-python/packages/source-python/players/_base.py
Fix to 9c7e4a22d5d465f705379457d5ce704ca0aa3eb6
=> Fixed Player.is_bot to be cached correctly.

addons/source-python/packages/source-python/entities/_base.py, addons/source-python/packages/source-python/listeners/tick.py
Added analogue for Entity.delay but for Repeat.
```python
def print_alive(player):
print('Alive')
player = Player(1)
repeat = player.register_repeat(print_alive, (player, ))
if player.dead:
repeat.stop() 
```
Garbage collecting for args of Repeat class.
```python
def __del__(self)
```
never will be called in a Entity subclass if you will pass reference to the instance of Entity object.  
The object remains in the memory forever.
For example:
```python
from random import random
from players.dictionary import PlayerDictionary
class CustomPlayer(Player):
def __init__(self, index):
super().__init__(index)
repeat = self.register_repeat(self._print_random_handler)
def __del__(self):
print('__del__')
def …
```
=> Entity.repeat

addons/source-python/packages/source-python/entities/_base.py, addons/source-python/packages/source-python/players/_base.py
* Added caching boolean argument for Player.from_userid.
=> Player.from_userid caching

src/core/modules/mathlib/mathlib.h, src/core/modules/mathlib/mathlib_wrap.cpp
Added VectorAngles and VectorVectors. #300
Reference:
https://developer.valvesoftware.com/wiki/AngleVectors()
https://github.com/alliedmodders/hl2sdk/blob/sdk2013/mathlib/mathlib_base.cpp#L903
https://github.com/alliedmodders/hl2sdk/blob/sdk2013/mathlib/mathlib_base.cpp#L921
https://github.com/alliedmodders/hl2sdk/blob/sdk2013/mathlib/mathlib_base.cpp#L500
=> Added VectorAngles and VectorVectors.

addons/source-python/data/source-python/entities/csgo/CBasePlayer.ini, addons/source-python/data/source-python/entities/csgo/CCSPlayer.ini
=> Updated CS:GO mvps and assists offsets.

addons/source-python/packages/source-python/__init__.py, addons/source-python/packages/source-python/listeners/__init__.py, src/core/modules/listeners/listeners_manager.cpp, src/core/modules/listeners/listeners_manager.h, src/core/modules/listeners/listeners_wrap.cpp
This PR adds lazy-loading support to ListenerManager so that hooks are only registered when a callback is first registered (to fix conflict with SourceMod, see #306).
The implementation is quite simple, when the first callback is registered, `ListenerManager.initialize` is called and `ListenerManager.finalize` is called when the last one is unregistered allowing us to add/remove our hooks only when requested.
=> Added lazy-loading support to ListenerManager.

addons/source-python/data/source-python/weapons/csgo.ini
Apparently some CS:GO update messed with the clip and maxammo properties again. Verified by buying an M4A1-S and checking the ammo values I got.
=> data: update m4a1_silencer clip and maxammo properties

addons/source-python/data/source-python/entities/csgo/CBaseCombatCharacter.ini, addons/source-python/packages/source-python/players/engines/csgo/__init__.py
I wanted to add the data for other games as well, but after testing the virtual function in HL2DM and CSS, I gave up. The function always returns True, even when it shouldn't. 
I'll see if the other [CBaseCombatCharacter::IsInFieldOfView()](https://github.com/alliedmodders/hl2sdk/blob/0ef5d3d482157bc0bb3aafd37c08961373f87bfd/game/shared/basecombatcharacter_shared.cpp#L615) function that takes an entity as an argument instead of a vector works in those games. 
If it does work, how should I handle different virtual functions that have the same name? Do I just change the name of the function in the data file? (**is_in_field_of_view** and **is_in_field_of_view_vec**)
Or is there some form of overloading we can do?
=> Added CBaseCombatCharacter::IsInFieldOfView data for CSGO.

addons/source-python/data/source-python/entities/orangebox/hl2mp/CBaseCombatWeapon.ini, addons/source-python/data/source-python/entities/orangebox/hl2mp/CItem.ini
Weapons and items in HL2DM are only spawned once. They get disabled when picked up by a player, and after a while (`sv_hl2mp_weapon_respawn_time`, `sv_hl2mp_item_respawn_time`) they are re-enabled.
As such, using an OnEntitySpawned/Created listener for these entities is pretty much pointless.
With [CItem::Materialize()](https://github.com/alliedmodders/hl2sdk/blob/0ef5d3d482157bc0bb3aafd37c08961373f87bfd/game/server/item_world.cpp#L486) and [CBaseCombatWeapon::Materialize()](https://github.com/alliedmodders/hl2sdk/blob/0ef5d3d482157bc0bb3aafd37c08961373f87bfd/game/server/basecombatweapon.cpp#L565), we can get access to these entities when they are re-enabled.
=> Added CItem::Materialize and CBaseCombatWeapon::Materialize data for HL2DM.

addons/source-python/data/source-python/weapons/csgo.ini
Added some missing data and fixed the incorrect name for weapon_bayonet.
=> Updated weapon data for CSGO.

addons/source-python/packages/source-python/memory/hooks.py, src/core/modules/memory/memory_hooks.cpp, src/core/modules/memory/memory_hooks.h, src/core/modules/memory/memory_wrap.cpp
Generic fix for issue #236
Test code:
```python
from memory.hooks import hooks_disabled
from entities.hooks import EntityPreHook, EntityCondition
from events import Event
@EntityPreHook(EntityCondition.is_human_player, 'on_take_damage')
def pre_take_damage(args):
print('take damage', args)
@Event('player_say')
def on_player_say(event):
player = Player.from_userid(event['userid'])
target = player.view_player
if target is None:
print('not a player or no target')
return
with hooks_disabled(event['text'] == 'yes'):
target.take_damage(5)
```
When looking at a player and typing ``yes``, the hook shouldn't get called. In all other cases the hook gets called.
=> Added the ability to disable hooks

addons/source-python/data/source-python/entities/csgo/CCSPlayer.ini, addons/source-python/packages/source-python/players/engines/csgo/__init__.py
Godmode granted through spawn protection or other sources within official gamemodes (deathmatch, arms race) isn't covered by the **m_takedamage** property. With this change, checking if a player has godmode in CSGO should always work.
=> Modified player.get_godmode() for CSGO.

addons/source-python/packages/source-python/commands/typed.py, addons/source-python/packages/source-python/menus/base.py
This change allows plugins to create menus without worrying about resources, since dynamically created menus are discarded.
=> Dynamic menus and translates TypedServerCommand.

src/core/modules/entities/entities_entity.cpp
This solves the problem of creating Non-networked entities.
This issue was discovered by @progre.
Code:
```python
from entities.entity import BaseEntity
BaseEntity.create("info_player_terrorist")
```
Output:
```
[SP] Caught an Exception:
ValueError: Conversion from "BaseEntity" (<_entities._entity.BaseEntity object at 0xed1eb980>) to "Index" failed.
The above exception was the direct cause of the following exception:
SystemError: <Boost.Python.function object at 0x9be5020> returned a result with an error set
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "../addons/source-python/packages/source-python/plugins/command.py", line 164, in load_plugin
plugin = self.manager.load(plugin_name)
File …
```
=> Fixed an issue where Non-networked entities could not be created.

addons/source-python/data/source-python/entities/CFogController.ini
Took me a while to realize why `AttributeError: Attribute "set_color_lerp_to" not found` kept popping up.
=> Fixed a typo in one of the CFogController inputs.

src/core/modules/memory/memory_function.cpp, src/core/modules/memory/memory_function.h, src/core/modules/memory/memory_wrap.cpp
This change allows hooked function to be called dynamically from other function libraries.
=> Add trampoline property to CFunction.

addons/source-python/data/source-python/entities/csgo/CBasePlayer.ini
Hello, thanks for an amazing project.
After seeing some weirdness with getting/setting player assist values in CS:GO, I did some investigation and it appears that the offset for assists has changed. I obtained these from running the snippet of commented code above the assists offset data on a CS:GO server on Windows and Linux:
Windows: `Offset of Player.assists is: 3204`
Linux: `Offset of Player.assists is: 3228`
This PR sets those values. Apologies if I missed something or have made a mistake. Thanks again!
=> Update CS:GO assists offset for Windows/Linux

src/core/modules/entities/entities_entity_wrap.cpp
Previous discussion: https://github.com/Source-Python-Dev-Team/Source.Python/issues/357
=> Removed caching of the physics_object property.

src/core/modules/entities/entities_wrap.cpp
When browsing the source code I noticed this typo which was binding "AddListenerEntity" to both add and remove entity listener on the python side.
This only gets called on SP unload so changing this probably doesn't actually do much in the end.
=> Fix remove entity listener

src/core/modules/net_channel/net_channel_wrap.cpp
This eliminates unnecessary condition checks.
Before:
```python
from core import SOURCE_ENGINE
player = Player(1)
if SOURCE_ENGINE in ("blade", "csgo", "l4d2"):
player.client.net_channel.send_file(file_name, transfer_id, False)
else:
player.client.net_channel.send_file(file_name, transfer_id)
```
After:
```python
player = Player(1)
player.client.net_channel.send_file(file_name, transfer_id)
```
=> Added default argument to Send/Deny/RequestFile functions.

addons/source-python/data/source-python/entities/csgo/CBaseCSGrenadeProjectile.ini, addons/source-python/packages/source-python/entities/engines/csgo/csgo.py
This function allows you to properly set the attacker on the Projectile.
If you think there is a problem with the name, please suggest a new name.
=> Added a set_attacker function to CBaseCSGrenadeProjectile for CS:GO.

addons/source-python/packages/source-python/core/__init__.py
This ensures the code that generates objects that expect `unload` in the custom packages works correctly.
```python
from core import AutoUnload
class Test(AutoUnload):
def __init__(self):
print("init Test")
def _unload_instance(self):
print("unloaded Test")
def test():
return Test()
```
```python
from test import Test
from test import test
Test()
test()
```
Output:
```
sp plugin load test_plugin
[SP] Loading plugin 'test_plugin'...
init Test
init Test
[SP] Successfully loaded plugin 'test_plugin'.
sp plugin unload test_plugin
[SP] Unloading plugin 'test_plugin'...
unloaded Test
unloaded Test
[SP] Successfully unloaded plugin 'test_plugin'.
```
=> Changed AutoUnload to be able to manage objects generated from custom packages.

addons/source-python/data/source-python/entities/csgo/CBasePlayer.ini, addons/source-python/data/source-python/entities/csgo/CCSPlayer.ini, addons/source-python/data/source-python/entities/orangebox/cstrike/CCSPlayer.ini, addons/source-python/packages/source-python/entities/classes.py, addons/source-python/packages/source-python/entities/datamaps.py
=> Added instance_property support to entity managers.

src/core/modules/memory/memory_function.cpp, src/core/modules/memory/memory_hooks.cpp, src/core/modules/memory/memory_pointer.cpp, src/core/modules/memory/memory_tools.h, src/core/modules/memory/memory_utilities.h
#334, #372, #373
When the object passed to ExtractPointer isn't the CPointer, the CPointer* generated by _ptr() will be released immediately.
Therefore, the CPointer* generated by ExtractPointer must not be retained.
The new Linux distributions have made this problem more apparent.
=> Fixed a problem with dangling references around ExtractPointer. (#334, #372, #373)

addons/source-python/packages/source-python/messages/impl.py
Tested in CSS and CSGO with:
```py
from messages.hooks import HookUserMessage
@HookUserMessage('ShowMenu')
def showmenu_pre(recipients, buffer):
print(recipients, buffer)
```
=> Added ShowMenu implementation

addons/source-python/data/source-python/entities/CEnvProjectedTexture.ini, addons/source-python/data/source-python/entities/csgo/CEnvProjectedTexture.ini, addons/source-python/data/source-python/entities/l4d2/CEnvProjectedTexture.ini, addons/source-python/data/source-python/entities/orangebox/CEnvProjectedTexture.ini
Tested the changes in HL2DM, CSS, and CSGO.
The only issue I ran into was the hardcoded [lightcolor](https://github.com/alliedmodders/hl2sdk/blob/hl2dm/game/server/env_projectedtexture.cpp#L158) keyvalue - setting the type as Color makes the data unusable: 
```
[SP] Caught an Exception:
Traceback (most recent call last):
File "..\addons\source-python\packages\source-python\commands\auth.py", line 44, in __call__
return self.callback(*args)
File "..\addons\source-python\plugins\flashlight\flashlight.py", line 52, in inspect_weapon
PlayerF(index).toggle_torch()
File "..\addons\source-python\plugins\flashlight\flashlight.py", line 111, in toggle_torch
owner_handle=self.inthandle
File "..\addons\source-python\plugins\flashlight\flashlight.py", line 157, in create
texture.light_color = color …
```
=> Split CEnvProjectedTexture data between different games.

src/core/sp_main.cpp
UnhookAllFunctions releases all m_pCallingConventions, but CFunctions held by AutoUnload such as EntityPreHook are not yet released, causing segmentation fault.
https://github.com/Source-Python-Dev-Team/Source.Python/blob/89273cd840e601094f31ade3ef601ce3a95f012c/src/core/modules/memory/memory_function.cpp#L199
UnhookAllFunctions has been moved to the end to deal with this.
=> Fixed referencing of released m_pCallingConvention on Source.Python unload.

addons/source-python/data/source-python/entities/csgo/CBasePlayer.ini, addons/source-python/data/source-python/entities/csgo/CCSPlayer.ini
=> Removed outdated offsets in CS:GO. (#388)

addons/source-python/packages/source-python/entities/classes.py, addons/source-python/packages/source-python/memory/manager.py
Fixed a problem where the pointer_attribute was not functioning properly because the offset was not set.
Also changed unnecessary call to create_type_from_file in _get_server_class.
=> Fixed TypeManager.pointer_attribute.

addons/source-python/docs/source-python/source/conf.py, addons/source-python/docs/source-python/source/contributing/building.rst, addons/source-python/docs/source-python/source/developing/events/csgo.rst, addons/source-python/docs/source-python/source/developing/getting-started.rst, addons/source-python/docs/source-python/source/developing/module_tutorials/listeners.rst, addons/source-python/docs/source-python/source/developing/module_tutorials/plugins.rst, addons/source-python/docs/source-python/source/general/reporting-a-bug.rst, addons/source-python/docs/source-python/source/index.rst
Updated the links on the main wiki page, added a bit more information about the player_blind event for CS:GO, and last but not least, made it so the copyright year remains up to date as long as the wiki is built at least once a year.
=> Fixed a couple of typos on the wiki.

addons/source-python/packages/source-python/memory/helpers.py, src/core/modules/memory/memory_function.cpp, src/core/modules/memory/memory_function.h, src/core/modules/memory/memory_wrap.cpp
If the Function has a converter, then the MemberFunction must also have a correct converter.
=> Fixed MemberFunction not returning the correct return type.

addons/source-python/packages/source-python/messages/hooks.py
This fixes the hooks from not getting called when the UserMessage was created/sent by a third-party plugin (SourceMod), but I'm not sure how to retrieve the actual UserMessage data (e.g. [ShowMenu data](https://github.com/Source-Python-Dev-Team/Source.Python/blob/35d34c885b2d787b265c99930d0fe09f5534668d/addons/source-python/packages/source-python/messages/impl.py#L181)).
=> Partial fix for issue #390.

src/core/modules/engines/engines_server_wrap.cpp
tf2 branch for hl2sdk updated recently. Some members in IServer and IVEngineServer have changed.
=> Update server functions for latest tf2 sdk branch

addons/source-python/data/source-python/entities/csgo/CBaseCombatCharacter.ini, addons/source-python/data/source-python/entities/csgo/CBasePlayer.ini, addons/source-python/data/source-python/entities/csgo/CCSPlayer.ini
Tested on Linux.
`is_in_field_of_view` and `blind` were checked with IDA for both Linux and Windows.
=> Updated CS:GO data(Operation Riptide).

addons/source-python/packages/source-python/listeners/__init__.py, src/core/modules/listeners/listeners_manager.cpp, src/core/modules/listeners/listeners_manager.h, src/core/modules/listeners/listeners_wrap.cpp, src/core/sp_main.cpp
Improved performance and eliminated hooks.
As a backwards compatibility break, when `CallGlobalChangeCallbacks` is blocked, the listener will no longer be emitted, but I don't think this will have any impact.
If there is a problem, I will reset to the hook.
=> Moved on_convar_changed_listener_manager to C++.

src/core/modules/memory/memory_function.cpp, src/thirdparty/dyncall/include/dyncall_config.h
When testing is_in_field_of_view(#417), the results were incorrect(#316), so I looked into it and found that the boolean was judging the whole value of eax (e.g. -27648 was True), which seems to be giving incorrect results.
I don't think this will break any existing plugins, but I can't be sure.
Test Code:
```python
from memory import Convention
from memory import DataType
player = Player(1)
player2 = Player(2)
is_in_field_of_view  = player.make_virtual_function(
276,
Convention.THISCALL, (
DataType.POINTER,
DataType.POINTER,
),
DataType.INT
)
print(player.is_in_field_of_view(player2.origin))
print(is_in_field_of_view(player, player2.origin) & 1)
print("int is_in_field_of_view", is_in_field_of_view(player, player2.origin))
```
=> Fixed a problem with Boolean in CFunction::Call.

addons/source-python/data/source-python/entities/csgo/CDecoyProjectile.ini, addons/source-python/data/source-python/entities/csgo/CFlashbangProjectile.ini, addons/source-python/data/source-python/entities/csgo/CHEGrenadeProjectile.ini, addons/source-python/data/source-python/entities/csgo/CMolotovProjectile.ini, addons/source-python/data/source-python/entities/csgo/CSensorGrenadeProjectile.ini, addons/source-python/data/source-python/entities/csgo/CSmokeGrenadeProjectile.ini
Tested on Linux and Windows.
Added functions and timer attribute to the weird CSensorGrenadeProjectile (tagrenade_projectile/weapon_tagrenade).
I added all the functions related to detonate. Which function to use depends on what you want the plugin to do. Normally, with Think_Arm, SensorThink is used for the next Think, and current_time+2.0 is put in the timer, but if you want to make it blow up immediately, you can choose either SensorThink or just DoDetectWave.
Also, you can detect the DetectWave by hooking Player.blind.
```python
from entities.hooks import EntityCondition
from entities.hooks import EntityPreHook
from memory import make_object
@EntityPreHook(EntityCondition.is_player, "blind")
def on_blind(args):
if (args[1] == 0.019999999552965164 and …
```
=> Updated projectile data for CS:GO.

addons/source-python/packages/source-python/weapons/restrictions.py
Classname of a certain weapons cannot be obtained by normal way.
https://developer.valvesoftware.com/wiki/Weapon_cz75a
> weapon_cz75a is a point entity available in Counter-Strike: Global Offensive .
> Warning: In the I/O system and in VScript, this entity is targeted with the classname weapon_p250 instead!
Code:
```python
from weapons.entity import Weapon
weapon_entity = Weapon.create("weapon_cz75a")
print("Weapon ClassName: ", weapon_entity.weapon_name)
print("Edict ClassName: ", weapon_entity.edict.classname)
```
Output:
```
Weapon ClassName:  weapon_cz75a
Edict ClassName:  weapon_p250
```
=> Fixed an issue with certain weapons restrictions not working properly.

addons/source-python/data/source-python/entities/bms/CBaseEntity.ini, addons/source-python/data/source-python/entities/csgo/CBaseEntity.ini, addons/source-python/data/source-python/entities/gmod/CBaseEntity.ini, addons/source-python/data/source-python/entities/l4d2/CBaseEntity.ini, addons/source-python/data/source-python/entities/orangebox/CBaseEntity.ini, addons/source-python/packages/source-python/entities/_base.py
I'm not sure if this only applies to CS:GO, but certain models seem to have problems with animation when the model is attached to player by model_index. It might be related to CCSGOPlayerAnimState::Reset(void) or something like that.
If the model is set by entity.model_index, the problem remains, but I can't decide what to do. Is it better to leave it as it is, as entity.model_name can't set the model?
Offsets other than Garry's Mod were borrowed from SourceMod, thanks to AlliedModders/SourceMod.
=> Fixed an animation error when setting a model to Player.

addons/source-python/packages/source-python/entities/_base.py
https://github.com/Source-Python-Dev-Team/Source.Python/pull/435#discussion_r751574447
=> Fixed crash of non-precached model for Entity.set_model.

src/core/modules/entities/entities_entity.cpp
I'm not sure why it raises excption when SendTableSharedExt::find_offset returns -1, but I changed it this way because certain entities/properties need to find the offset from the datamap.
Code(CS:GO/Linux):
```python
from entities.entity import Entity
beam = Entity.create("env_beam")
print(beam.effects)
```
Output:
```
[SP] Caught an Exception:
Traceback (most recent call last):
File "../addons/source-python/packages/source-python/plugins/command.py", line 164, in load_plugin
plugin = self.manager.load(plugin_name)
File "../addons/source-python/packages/source-python/plugins/manager.py", line 207, in load
plugin._load()
File "../addons/source-python/packages/source-python/plugins/instance.py", line 74, in _load
self.module = import_module(self.import_name)
File …
```
=> Changed GetEffects/SetEffects to DatamapProperty.

src/core/modules/players/players_wrap.cpp, src/core/modules/players/players_wrap.h
This allows us to reference various properties even when we only have access to the Client.
is_connected/is_spawned/is_active/is_fake_client/is_hltv/is_human_player were made into functions to match the other types.
=> Exported more property and functions from IClient.

addons/source-python/packages/source-python/players/voice.py
Hooking SetClientListening is not cheap, even though it's done only once every 20 ticks, since it calls player count * 64 times.
The best way would be to implement it on C++ side, but this would at least eliminate unnecessary hook.
=> Changed mute_manager to not hook SetClientListening until player is muted.

addons/source-python/data/source-python/entities/orangebox/hl2mp/CBaseCombatCharacter.ini, addons/source-python/data/source-python/entities/orangebox/hl2mp/CBaseCombatWeapon.ini, addons/source-python/data/source-python/entities/orangebox/hl2mp/CBaseEntity.ini, addons/source-python/data/source-python/entities/orangebox/hl2mp/CBaseGrenade.ini, addons/source-python/data/source-python/entities/orangebox/hl2mp/CBasePlayer.ini, addons/source-python/data/source-python/entities/orangebox/hl2mp/CItem.ini
=> Updated HL2:DM data. (#500)

addons/source-python/packages/source-python/listeners/tick.py
Fix for #498.
Changed Repeat.total_time_remaining to return 0 since there is no rational reason for it to return None when there is no delay or when Repeat is finished.
=> Fixed incorrect Repeat.total_time_remaining. (#498)

addons/source-python/packages/source-python/menus/base.py, addons/source-python/packages/source-python/menus/esc.py, addons/source-python/packages/source-python/menus/radio.py
Sometimes it is not necessary to show navigation, for example, in the admin menu (as in SM)
=> Allow to hide information about pages in the menu

addons/source-python/packages/source-python/engines/precache.py, addons/source-python/packages/source-python/engines/sound.py
This fixes the following error when unloading the plugin
Output:
```
[Source.Python]
[SP] Caught an Exception:
Traceback (most recent call last):
File "..\addons\source-python\packages\source-python\plugins\manager.py", line 437, in _unload_auto_unload_instances
instance._unload_instance()
File "..\addons\source-python\packages\source-python\engines\sound.py", line 292, in _unload_instance
self._downloads._unload_instance()
File "..\addons\source-python\packages\source-python\stringtables\downloads.py", line 98, in _unload_instance
_downloadables_list.remove(self)
ValueError: list.remove(x): x not in list
```
=> Removed unnecessary _BaseSound._unload_instance function.

src/core/modules/entities/entities_entity.cpp
This fixes a problem with func_bomb_target not able to get BombExplode, etc.
=> Fixes an error caused when the name of BaseEntityOutput is overlapped with another DataDesc.

src/core/modules/players/players_entity.h
It appears they've changed the property for eye angles from **m_angEyeAngles** to **hl2mpnonlocaldata.m_angEyeAngles**.
=> Fixed the eye angle property for HL2DM.
